### PR TITLE
Create all-tabs.rkt

### PR DESCRIPTION
**Pull request by spdegabrielle**

### CODE REVIEW

**Comment by spdegabrielle** [comment]
#6

**Comment by Metaxal** [comment]
Thanks for this!
The README should actually be generated automatically from the `make-readme.sh` script, which gathers the doc-strings in the script files, declared with `(script-help-string ...)` (see any other script). It will sort them alphabetically too. Can I let you take care of this?

**Comment by spdegabrielle** [comment]
I've added the script-help-string and removed the change to README. Can you squash?

**Comment by Metaxal** [comment]
Can you run the `make-readme.sh` script yourself also?

(Don't care about squashing, it's not like there are thousands of commits in this repo.)

**Comment by spdegabrielle** [comment]
Oops - I misunderstood - will do.

**Comment by spdegabrielle** [comment]
I've run `make-readme.sh` its changes are now included.

**Comment by Metaxal** [comment]
That's perfect, thanks a bunch Stephen!

**Pull request merged**
