### PR TITLE
Create more-scripts.rkt

### PR DESCRIPTION
**Pull request by spdegabrielle**

### CODE REVIEW

**Comment by Metaxal** [comment]
Suggestion to discuss: How about placing this in the `url2script` menu instead? The link also directs to other packages, but that should be fine.

**Comment by Metaxal** [comment]
Related to https://github.com/Metaxal/quickscript/issues/24

**Comment by spdegabrielle** [comment]
yes, 

I would go further - I think both belong in `Manage Scripts`
failing that I think `url2script` and `more-scripts` should be at the top level

It should have a high profile.

**Comment by spdegabrielle** [comment]
I have moved it to the url2script menu

**Comment by Metaxal** [comment]
Thanks!

**Comment by Metaxal** [comment]
I merged more-scripts into url2script—it made more sense.

**Pull request merged**
